name: TournoiPvP
version: 1.0.1
author: LowTix_
main: eu.pvpwarcraft.tournoipvp.TournoiPvP
commands:
  inscription:
    aliases: [insc]
  tournoi:
    aliases: [tour]
  tournoiinfo:
    aliases: [tinfo]