#########################################################
#-------------------------------------------------------#
#                   » PLUGIN DAYZ «                     #                   
#                         BY                            #                          
#                 LowTix_ & LeFlodu72                   #
#-------------------------------------------------------#          
#########################################################

#---# VIDE #---#
pouet: 1

#########################################################
#-------------------------------------------------------#
#                   » PLUGIN DAYZ «                     #                   
#                         BY                            #                          
#                 LowTix_ & LeFlodu72                   #
#-------------------------------------------------------#          
#########################################################